version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - chroma_data:/app/chroma_data
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped

volumes:
  chroma_data: